DROP DATABASE IF EXISTS ocs;
DROP DATABASE IF EXISTS bss;
DROP DATABASE IF EXISTS history;
CREATE DATABASE ocs
  WITH ENCODING='UTF8'
       OWNER=postgres
       CONNECTION LIMIT=-1;


CREATE DATABASE bss
  WITH ENCODING='UTF8'
       OWNER=postgres
       CONNECTION LIMIT=-1;


CREATE DATABASE history
  WITH ENCODING='UTF8'
       OWNER=postgres
       CONNECTION LIMIT=-1;